# Generated by Django 2.2.2 on 2019-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('cover_image', models.ImageField(null=True, upload_to='media/futsal_cover')),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('venue_name',),
            },
        ),
    ]
